[project]
name = "brokers-api-tests"
version = "0.1.0"
description = ""
authors = [
    {name = "Telepnef",email = "telepnef@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "pytest (>=9.0.2,<10.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "kafka-python (>=2.3.0,<3.0.0)",
    "pika (>=1.3.2,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poetry]
package-mode = false
